name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Shiv-Github21
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=dark
      
      - name: Push to output branch
        uses: EndBug/add-and-commit@v9
        with:
          default_branch: output
          branch: output
          message: 'Generate Contribution Snake'
          add: 'dist'
          pull_strategy: 'NO-PULL'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
